on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 12 * * *"

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - uses: denoland/setup-deno@v1
          with:
            deno-version: "1.26.0"

        - run: mkdir -p dist/currency

        - run: deno run --allow-all get-currencies.ts

        - uses: JamesIves/github-pages-deploy-action@4.1.0
          with:
            branch: gh-pages
            folder: dist